apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-springboot-react-backend
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://gitlab.com/jerrybai/student-springboot-react-backend.git
    targetRevision: HEAD
    path: dev
  
  destination:
    server: https://kubernetes.default.svc
    namespace: student-springboot-react-backend

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true