apiVersion: v1
kind: Service
metadata:
  name: student-springboot-react-backend
spec:
  selector:
    app: student-springboot-react-backend
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000